name: Build and deploy Angular app to Azure Web App - medicalplatform-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Upload Angular build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-app
          path: dist/medicalPlatform-frontend/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Angular build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app
          path: angular-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BB20F5F2EA8944B283C13F0B96DE14F7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BEBA37C709D5417093F9217144D771A8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21CCDB7BC49846B395E47FBA46E8055A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'medicalplatform-frontend'
          slot-name: 'Production'
          package: angular-app
